In [7]:
import pandas as pd
import re
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import cdsapi
import copernicusmarine

c:\Users\aleks\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Let us read the data:

In [2]:
file_name = "PositionReport.xlsx"
df = pd.read_excel(file_name)
print("\nFound columns:")
print(df.columns.tolist())

print("\nFirst 10 rows of the data:")
print(df.head(10))

Found columns:
['VESSEL', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7']

First 10 rows of the data:
                           VESSEL      Unnamed: 1       Unnamed: 2  \
0                             NaN             NaN              NaN
1                            From             NaN              NaN
2                              To             NaN              NaN
3                             NaN             NaN              NaN
4    Total miles (w/speed ≥ 1 kn)             NaN              NaN
5  Average speed (w/speed ≥ 5 kn)             NaN              NaN
6                             NaN             NaN              NaN
7                            Time             Lat              Lon
8                             NaN             NaN              NaN
9             2023-02-02 00:06:00  56° 49.6000' N  000° 07.7000' W

            Unnamed: 3               Unnamed: 4   Unnamed: 5  \
0                  NaN                      NaN          NaN
1  2023-02-02 00:00:00                      NaN          NaN
2  2026-02-02 23:59:59                      NaN          NaN
3                  NaN                      NaN          NaN
4         200729.49121                      NaN          NaN
5            11.591828                      NaN          NaN
6                  NaN                      NaN          NaN
7          Speed\n[kn]  Calculated\nSpeed\n[kn]  Course\n[°]
8                  NaN                      NaN          NaN
9                   15                      NaN          357

                         Unnamed: 6                 Unnamed: 7
0                               NaN                        NaN
1                               NaN                        NaN
2                               NaN                        NaN
3                               NaN                        NaN
4                               NaN                         nm
5                               NaN                         kn
6                               NaN                        NaN
7  Distance since\nlast point\n[nm]  Total distance\nrun\n[nm]
8                               NaN                        NaN
9                                 0                          0

What can be seen in the data is the fact that the header starts at row 9. Therefore, first 8 rows should be skipped.

In [18]:
df_position = pd.read_excel('PositionReport.xlsx', sheet_name='SC CONNECTOR', skiprows=8)

In [19]:
print("Data shape:", df_position.shape)
display(df_position.head(10))

Data shape: (156943, 8)

,Time,Lat,Lon,Speed\n[kn],Calculated\nSpeed\n[kn],Course\n[°],Distance since\nlast point\n[nm],Total distance\nrun\n[nm]
0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-02-02 00:06:00,56° 49.6000' N,000° 07.7000' W,15.0,NaN,357.0,0.000000,0.000000
2,2023-02-02 00:21:00,56° 53.2000' N,000° 07.5000' W,15.0,14.4,47.0,3.608126,3.608126
3,2023-02-02 00:33:00,56° 55.4000' N,000° 03.5000' W,16.0,15.5,46.0,3.105603,6.713728
4,2023-02-02 00:54:00,56° 59.2000' N,000° 03.3000' E,15.0,15.2,44.0,5.318924,12.032653
5,2023-02-02 01:15:00,57° 03.0000' N,000° 10.5000' E,16.0,15.6,46.0,5.468927,17.501580
6,2023-02-02 01:33:00,57° 06.3000' N,000° 16.8000' E,16.0,15.9,48.0,4.763985,22.265565
7,2023-02-02 01:45:50,57° 08.4690' N,000° 21.3304' E,16.0,15.4,48.0,3.285002,25.550568
8,2023-02-02 01:58:32,57° 10.7088' N,000° 25.9707' E,16.2,15.9,47.0,3.374881,28.925449
9,2023-02-02 02:10:15,57° 12.6930' N,000° 30.4486' E,15.9,16.1,50.0,3.139759,32.065207

In [20]:
print("Data shape before cleaning:", df_position.shape)

df_position = df_position.dropna(subset=['Time']).reset_index(drop=True)

df_position.columns = df_position.columns.str.replace('\n', ' ')

# standarization of the column names standarization
rename_dict = {'Speed [kn]': 'Speed_kn', 'Calculated Speed [kn]': 'Calc_Speed_kn', 'Course [°]': 'Course_deg', 'Distance since last point [nm]': 'Dist_since_last_nm', 'Total distance run [nm]': 'Total_dist_nm'}

df_position = df_position.rename(columns=rename_dict)

print("Data shape after cleaning", df_position.shape)
display(df_position.head(10))

Data shape before cleaning: (156943, 8)
Data shape after cleaning (156942, 8)

,Time,Lat,Lon,Speed_kn,Calc_Speed_kn,Course_deg,Dist_since_last_nm,Total_dist_nm
0,2023-02-02 00:06:00,56° 49.6000' N,000° 07.7000' W,15.0,NaN,357.0,0.000000,0.000000
1,2023-02-02 00:21:00,56° 53.2000' N,000° 07.5000' W,15.0,14.4,47.0,3.608126,3.608126
2,2023-02-02 00:33:00,56° 55.4000' N,000° 03.5000' W,16.0,15.5,46.0,3.105603,6.713728
3,2023-02-02 00:54:00,56° 59.2000' N,000° 03.3000' E,15.0,15.2,44.0,5.318924,12.032653
4,2023-02-02 01:15:00,57° 03.0000' N,000° 10.5000' E,16.0,15.6,46.0,5.468927,17.501580
5,2023-02-02 01:33:00,57° 06.3000' N,000° 16.8000' E,16.0,15.9,48.0,4.763985,22.265565
6,2023-02-02 01:45:50,57° 08.4690' N,000° 21.3304' E,16.0,15.4,48.0,3.285002,25.550568
7,2023-02-02 01:58:32,57° 10.7088' N,000° 25.9707' E,16.2,15.9,47.0,3.374881,28.925449
8,2023-02-02 02:10:15,57° 12.6930' N,000° 30.4486' E,15.9,16.1,50.0,3.139759,32.065207
9,2023-02-02 02:24:00,57° 15.1000' N,000° 35.9000' E,16.0,16.6,50.0,3.814630,35.879838

Apart from the 'nice formatting' of the Excel file, there is another aspect to consider. From human perspective, the 56° 49.6000' N notation is highly readable. Howeber, for a computer this notation is treated as a string not a particular number. Therefore, we need to tranform it into a floating-point number, 56.8266.

In [21]:
def parse_coordinates(coord_str):
    """
    Changing "56° 49.6000' N" string format for a decimal (float) format.
    """

    if pd.isna(coord_str):
        return np.nan

    match = re.search(r"(\d+)\s*°\s*([\d\.]+)\s*'\s*([NSEW])", str(coord_str))

    if match:
        degrees = float(match.group(1))
        minutes = float(match.group(2))
        direction = match.group(3)

        decimal = degrees + (minutes / 60.0)

        if direction in ['S', 'W']:
            decimal = -decimal

        return decimal
    return np.nan


df_position['Lat_dec'] = df_position['Lat'].apply(parse_coordinates)
df_position['Lon_dec'] = df_position['Lon'].apply(parse_coordinates)

display(df_position[['Lat', 'Lat_dec', 'Lon', 'Lon_dec']].head()) # comparing all columns - old ones - with the old notation and new ones - with the new notation

              Lat    Lat_dec              Lon   Lon_dec
0  56° 49.6000' N  56.826667  000° 07.7000' W -0.128333
1  56° 53.2000' N  56.886667  000° 07.5000' W -0.125000
2  56° 55.4000' N  56.923333  000° 03.5000' W -0.058333
3  56° 59.2000' N  56.986667  000° 03.3000' E  0.055000
4  57° 03.0000' N  57.050000  000° 10.5000' E  0.175000

In [22]:
df_position = df_position.drop(columns=['Lat', 'Lon'])
df_position = df_position.rename(columns={'Lat_dec': 'Lat', 'Lon_dec': 'Lon'})

order = [
    'Time', 'Lat', 'Lon', 'Speed_kn', 'Calc_Speed_kn', 'Course_deg',
    'Dist_since_last_nm', 'Total_dist_nm'
]

df_position = df_position[order]

print("Columns after dropping old and renaming new ones:")
print(df_position.columns.tolist())

df_position.to_csv('PositionReport_cleaned.csv', index=False)

Columns after dropping old and renaming new ones:
['Time', 'Lat', 'Lon', 'Speed_kn', 'Calc_Speed_kn', 'Course_deg', 'Dist_since_last_nm', 'Total_dist_nm']

Now, we need to analyze the bounding box for the SC CONNECTOR - the furthest points North, South, East and West that the ship reached and the years in which it sailed.

In [24]:
df = pd.read_csv('PositionReport_cleaned.csv')

# time conversion (in datetime format)
df['Time'] = pd.to_datetime(df['Time']) 

# bounding box with some margin (0.5 degrees)
margin = 0.5 
north = round(df['Lat'].max() + margin, 2)
south = round(df['Lat'].min() - margin, 2)
east = round(df['Lon'].max() + margin, 2)
west = round(df['Lon'].min() - margin, 2)

print(f"Bounding box: North = {north}, South = {south}, East = {east}, West = {west}")

years = df['Time'].dt.strftime('%Y').unique().tolist()
print("Years in the dataset:", years)

Bounding box: North = 61.73, South = 50.54, East = 11.7, West = -2.62
Years in the dataset: ['2023', '2024', '2025', '2026']

In [ ]:
URL = "https://cds.climate.copernicus.eu/api"
KEY = "KEY" 

client = cdsapi.Client(url=URL, key=KEY)

bounding_box = [61.73, -2.62, 50.54, 11.7]

years = ['2023', '2024', '2025', '2026']

all_months = [str(i).zfill(2) for i in range(1, 13)]
all_days = [str(i).zfill(2) for i in range(1, 32)]
all_hours = [f"{str(i).zfill(2)}:00" for i in range(24)]


for year in years:
    print(f"--- YEAR {year} ---")
    
    # wind (u, v)
    wind_nc = f"wind_{year}.nc"

    wind = {
        "product_type": ["reanalysis"],
        "variable": ["10m_u_component_of_wind", "10m_v_component_of_wind"],
        "year": [year],
        "month": all_months,
        "day": all_days,
        "time": all_hours,
        "data_format": "netcdf",
        "download_format": "unarchived",
        "area": bounding_box
    }
    client.retrieve("reanalysis-era5-single-levels", wind, wind_nc)
    

    # waves (H_s)
    waves_nc = f"waves_{year}.nc"

    waves = {
        "product_type": ["reanalysis"],
        "variable": ["significant_height_of_combined_wind_waves_and_swell"],
        "year": [year],
        "month": all_months,
        "day": all_days,
        "time": all_hours,
        "data_format": "netcdf",
        "download_format": "unarchived",
        "area": bounding_box
    }   
    client.retrieve("reanalysis-era5-single-levels", waves, waves_nc)

--- YEAR 2023 ---

2026-04-12 21:31:29,424 INFO [2025-12-11T00:00:00] Please note that a dedicated catalogue entry for this dataset, post-processed and stored in Analysis Ready Cloud Optimized (ARCO) format (Zarr), is available for optimised time-series retrievals (i.e. for retrieving data from selected variables for a single point over an extended period of time in an efficient way). You can discover it [here](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels-timeseries?tab=overview)
2026-04-12 21:31:29,425 INFO Request ID is 0c3f1b73-b024-4ba8-8561-68d470d5a912
2026-04-12 21:31:29,494 INFO status has been updated to accepted
2026-04-12 21:31:43,176 INFO status has been updated to running
2026-04-12 21:43:52,453 INFO status has been updated to successful
2026-04-12 21:44:35,325 INFO [2025-12-11T00:00:00] Please note that a dedicated catalogue entry for this dataset, post-processed and stored in Analysis Ready Cloud Optimized (ARCO) format (Zarr), is available for optimised time-series retrievals (i.e. for retrieving data from selected variables for a single point over an extended period of time in an efficient way). You can discover it [here](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels-timeseries?tab=overview)
2026-04-12 21:44:35,326 INFO Request ID is 44a272e1-d8d2-4a75-b827-1dd40ba7b70d
2026-04-12 21:44:35,402 INFO status has been updated to accepted
2026-04-12 21:45:08,360 INFO status has been updated to running
2026-04-12 21:51:26,412 INFO status has been updated to successful

--- YEAR 2024 ---

2026-04-12 21:51:31,020 INFO [2025-12-11T00:00:00] Please note that a dedicated catalogue entry for this dataset, post-processed and stored in Analysis Ready Cloud Optimized (ARCO) format (Zarr), is available for optimised time-series retrievals (i.e. for retrieving data from selected variables for a single point over an extended period of time in an efficient way). You can discover it [here](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels-timeseries?tab=overview)
2026-04-12 21:51:31,020 INFO Request ID is f5e65a8c-dc32-4998-a6e8-9f8f4dfb60f9
2026-04-12 21:51:31,106 INFO status has been updated to accepted
2026-04-12 21:51:39,737 INFO status has been updated to running
2026-04-12 22:03:53,488 INFO status has been updated to successful
2026-04-12 22:04:21,225 INFO [2025-12-11T00:00:00] Please note that a dedicated catalogue entry for this dataset, post-processed and stored in Analysis Ready Cloud Optimized (ARCO) format (Zarr), is available for optimised time-series retrievals (i.e. for retrieving data from selected variables for a single point over an extended period of time in an efficient way). You can discover it [here](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels-timeseries?tab=overview)
2026-04-12 22:04:21,225 INFO Request ID is 8e270d4e-19e4-4897-a469-e359d10d31b1
2026-04-12 22:04:21,302 INFO status has been updated to accepted
2026-04-12 22:04:54,084 INFO status has been updated to running
2026-04-12 22:10:41,546 INFO status has been updated to successful

--- YEAR 2025 ---

2026-04-12 22:10:46,053 INFO [2025-12-11T00:00:00] Please note that a dedicated catalogue entry for this dataset, post-processed and stored in Analysis Ready Cloud Optimized (ARCO) format (Zarr), is available for optimised time-series retrievals (i.e. for retrieving data from selected variables for a single point over an extended period of time in an efficient way). You can discover it [here](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels-timeseries?tab=overview)
2026-04-12 22:10:46,054 INFO Request ID is 4cabdf54-4cbe-44c0-995b-1909537a258c
2026-04-12 22:10:46,129 INFO status has been updated to accepted
2026-04-12 22:10:59,814 INFO status has been updated to running
2026-04-12 22:21:08,050 INFO status has been updated to successful
2026-04-12 22:21:43,550 INFO [2025-12-11T00:00:00] Please note that a dedicated catalogue entry for this dataset, post-processed and stored in Analysis Ready Cloud Optimized (ARCO) format (Zarr), is available for optimised time-series retrievals (i.e. for retrieving data from selected variables for a single point over an extended period of time in an efficient way). You can discover it [here](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels-timeseries?tab=overview)
2026-04-12 22:21:43,551 INFO Request ID is 8764f207-8df7-45d5-b454-3f31feab3dc3
2026-04-12 22:21:43,622 INFO status has been updated to accepted
2026-04-12 22:21:57,275 INFO status has been updated to running
2026-04-12 22:28:03,983 INFO status has been updated to successful

--- YEAR 2026 ---

2026-04-12 22:28:09,582 INFO [2025-12-11T00:00:00] Please note that a dedicated catalogue entry for this dataset, post-processed and stored in Analysis Ready Cloud Optimized (ARCO) format (Zarr), is available for optimised time-series retrievals (i.e. for retrieving data from selected variables for a single point over an extended period of time in an efficient way). You can discover it [here](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels-timeseries?tab=overview)
2026-04-12 22:28:09,582 INFO Request ID is 6c86ec9b-f64a-41f4-9580-827c00c7e0cb
2026-04-12 22:28:09,654 INFO status has been updated to accepted
2026-04-12 22:28:23,215 INFO status has been updated to running
Recovering from connection error [HTTPSConnectionPool(host='cds.climate.copernicus.eu', port=443): Max retries exceeded with url: /api/retrieve/v1/jobs/6c86ec9b-f64a-41f4-9580-827c00c7e0cb?log=True&request=True (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000015B17EEBD40>: Failed to resolve 'cds.climate.copernicus.eu' ([Errno 11001] getaddrinfo failed)"))], attempt 1 of 500
Retrying in 120 seconds
2026-04-12 22:51:20,301 INFO status has been updated to successful
2026-04-12 22:51:28,001 INFO [2025-12-11T00:00:00] Please note that a dedicated catalogue entry for this dataset, post-processed and stored in Analysis Ready Cloud Optimized (ARCO) format (Zarr), is available for optimised time-series retrievals (i.e. for retrieving data from selected variables for a single point over an extended period of time in an efficient way). You can discover it [here](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels-timeseries?tab=overview)
2026-04-12 22:51:28,001 INFO Request ID is 421c9fe1-57b9-468f-9b16-bf47d5fb9b80
2026-04-12 22:51:28,090 INFO status has been updated to accepted
2026-04-12 22:51:36,505 INFO status has been updated to running
2026-04-12 22:53:22,135 INFO status has been updated to successful

Taking into account additional variables from ERA5:

In [ ]:

URL = "https://cds.climate.copernicus.eu/api"
KEY = "KEY" 

client = cdsapi.Client(url=URL, key=KEY)

bounding_box = [61.73, -2.62, 50.54, 11.7]
years = ['2023', '2024', '2025', '2026']

all_months = [str(i).zfill(2) for i in range(1, 13)]
all_days = [str(i).zfill(2) for i in range(1, 32)]
all_hours = [f"{str(i).zfill(2)}:00" for i in range(24)]


for year in years:
    print(f"--- YEAR {year} ---")
    
    # additional wave parameters (direction and period)
    wave_extra_nc = f"wave_ext_{year}.nc"
    wave_extra = {
        "product_type": ["reanalysis"],
        "variable": [
            "mean_wave_direction", 
            "mean_wave_period"
        ],
        "year": [year],
        "month": all_months,
        "day": all_days,
        "time": all_hours,
        "data_format": "netcdf",
        "download_format": "unarchived",
        "area": bounding_box
    }
    
    client.retrieve("reanalysis-era5-single-levels", wave_extra, wave_extra_nc)

    # areodynamics (air density and gusts)
    wind_extra_nc = f"wind_extra_{year}.nc"
    wind_extra = {
        "product_type": ["reanalysis"],
        "variable": [
            "air_density_over_the_oceans", 
            "10m_wind_gust_since_previous_post_processing"
        ],
        "year": [year],
        "month": all_months,
        "day": all_days,
        "time": all_hours,
        "data_format": "netcdf",
        "download_format": "unarchived",
        "area": bounding_box
    }
    
    client.retrieve("reanalysis-era5-single-levels", wind_extra, wind_extra_nc)

--- YEAR 2023 ---

2026-04-13 17:13:17,168 INFO [2025-12-11T00:00:00] Please note that a dedicated catalogue entry for this dataset, post-processed and stored in Analysis Ready Cloud Optimized (ARCO) format (Zarr), is available for optimised time-series retrievals (i.e. for retrieving data from selected variables for a single point over an extended period of time in an efficient way). You can discover it [here](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels-timeseries?tab=overview)
2026-04-13 17:13:17,171 INFO Request ID is c3646484-6b1b-401b-a654-5cd50e68520e
2026-04-13 17:13:17,255 INFO status has been updated to accepted
2026-04-13 17:13:31,033 INFO status has been updated to running
2026-04-13 17:23:40,117 INFO status has been updated to successful
2026-04-13 17:23:45,663 INFO [2025-12-11T00:00:00] Please note that a dedicated catalogue entry for this dataset, post-processed and stored in Analysis Ready Cloud Optimized (ARCO) format (Zarr), is available for optimised time-series retrievals (i.e. for retrieving data from selected variables for a single point over an extended period of time in an efficient way). You can discover it [here](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels-timeseries?tab=overview)
2026-04-13 17:23:45,663 INFO Request ID is 75fc9401-0ccc-4276-b1d0-a8b8b9f976e1
2026-04-13 17:23:45,763 INFO status has been updated to accepted
2026-04-13 17:24:07,051 INFO status has been updated to running
2026-04-13 17:44:11,643 INFO status has been updated to successful

--- YEAR 2024 ---

2026-04-13 17:44:32,820 INFO [2025-12-11T00:00:00] Please note that a dedicated catalogue entry for this dataset, post-processed and stored in Analysis Ready Cloud Optimized (ARCO) format (Zarr), is available for optimised time-series retrievals (i.e. for retrieving data from selected variables for a single point over an extended period of time in an efficient way). You can discover it [here](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels-timeseries?tab=overview)
2026-04-13 17:44:32,821 INFO Request ID is 6fe872b0-3db6-4666-a2aa-384b173e028a
2026-04-13 17:44:32,933 INFO status has been updated to accepted
2026-04-13 17:44:54,209 INFO status has been updated to running
2026-04-13 17:56:55,630 INFO status has been updated to successful
2026-04-13 17:57:01,494 INFO [2025-12-11T00:00:00] Please note that a dedicated catalogue entry for this dataset, post-processed and stored in Analysis Ready Cloud Optimized (ARCO) format (Zarr), is available for optimised time-series retrievals (i.e. for retrieving data from selected variables for a single point over an extended period of time in an efficient way). You can discover it [here](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels-timeseries?tab=overview)
2026-04-13 17:57:01,495 INFO Request ID is c2847697-ce22-4687-9744-ba3794bdf7f1
2026-04-13 17:57:01,808 INFO status has been updated to accepted
2026-04-13 17:57:23,026 INFO status has been updated to running
Recovering from connection error [HTTPSConnectionPool(host='cds.climate.copernicus.eu', port=443): Max retries exceeded with url: /api/retrieve/v1/jobs/c2847697-ce22-4687-9744-ba3794bdf7f1?log=True&request=True (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021ABABAE720>: Failed to resolve 'cds.climate.copernicus.eu' ([Errno 11001] getaddrinfo failed)"))], attempt 1 of 500
Retrying in 120 seconds
2026-04-13 18:17:46,238 INFO status has been updated to successful

--- YEAR 2025 ---

2026-04-13 18:17:56,961 INFO [2025-12-11T00:00:00] Please note that a dedicated catalogue entry for this dataset, post-processed and stored in Analysis Ready Cloud Optimized (ARCO) format (Zarr), is available for optimised time-series retrievals (i.e. for retrieving data from selected variables for a single point over an extended period of time in an efficient way). You can discover it [here](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels-timeseries?tab=overview)
2026-04-13 18:17:56,962 INFO Request ID is 76e79e47-2507-4ba3-b3d4-2f77a2e4f05b
2026-04-13 18:17:57,036 INFO status has been updated to accepted
2026-04-13 18:18:10,602 INFO status has been updated to running
2026-04-13 18:28:18,698 INFO status has been updated to successful
2026-04-13 18:28:22,978 INFO [2025-12-11T00:00:00] Please note that a dedicated catalogue entry for this dataset, post-processed and stored in Analysis Ready Cloud Optimized (ARCO) format (Zarr), is available for optimised time-series retrievals (i.e. for retrieving data from selected variables for a single point over an extended period of time in an efficient way). You can discover it [here](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels-timeseries?tab=overview)
2026-04-13 18:28:22,979 INFO Request ID is a2a4f13d-1f3e-46a5-8a55-dbecfc036fa9
2026-04-13 18:28:23,058 INFO status has been updated to accepted
2026-04-13 18:28:36,639 INFO status has been updated to running
2026-04-13 18:48:47,651 INFO status has been updated to successful

--- YEAR 2026 ---

2026-04-13 18:48:58,151 INFO [2025-12-11T00:00:00] Please note that a dedicated catalogue entry for this dataset, post-processed and stored in Analysis Ready Cloud Optimized (ARCO) format (Zarr), is available for optimised time-series retrievals (i.e. for retrieving data from selected variables for a single point over an extended period of time in an efficient way). You can discover it [here](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels-timeseries?tab=overview)
2026-04-13 18:48:58,152 INFO Request ID is 820d6565-e3a6-46dd-ac8f-ab820ccd7a42
2026-04-13 18:48:58,226 INFO status has been updated to accepted
2026-04-13 18:49:11,753 INFO status has been updated to running
2026-04-13 18:53:17,826 INFO status has been updated to successful
2026-04-13 18:53:20,206 INFO [2025-12-11T00:00:00] Please note that a dedicated catalogue entry for this dataset, post-processed and stored in Analysis Ready Cloud Optimized (ARCO) format (Zarr), is available for optimised time-series retrievals (i.e. for retrieving data from selected variables for a single point over an extended period of time in an efficient way). You can discover it [here](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels-timeseries?tab=overview)
2026-04-13 18:53:20,207 INFO Request ID is 1098f45c-acc2-438f-a1ef-1880bdc4608e
2026-04-13 18:53:20,287 INFO status has been updated to accepted
2026-04-13 18:53:41,534 INFO status has been updated to running
2026-04-13 18:59:40,499 INFO status has been updated to successful

In [6]:
pip install copernicusmarine

Collecting copernicusmarineNote: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

  Obtaining dependency information for copernicusmarine from https://files.pythonhosted.org/packages/e8/b7/4a3e7885c524cc1da667c414e97ac12a81051596146bec99e0113429f759/copernicusmarine-2.3.0-py3-none-any.whl.metadata
  Downloading copernicusmarine-2.3.0-py3-none-any.whl.metadata (8.2 kB)
Collecting arcosparse<0.5.0,>=0.4.2 (from copernicusmarine)
  Obtaining dependency information for arcosparse<0.5.0,>=0.4.2 from https://files.pythonhosted.org/packages/34/ec/c764296b694b425853baf444d9e4643949d2e16479f5b192f47fa24ba1fe/arcosparse-0.4.2-py3-none-any.whl.metadata
  Downloading arcosparse-0.4.2-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: boto3>=1.26 in c:\users\aleks\appdata\roaming\python\python312\site-packages (from copernicusmarine) (1.42.30)
Requirement already satisfied: click!=8.2.0,<8.3.0,>=8.0.4 in c:\users\aleks\appdata\local\programs\python\python312\lib\site-packages (from copernicusmarine) (8.1.7)
Requirement already satisfied: dask>=2022 in c:\users\aleks\appdata\local\programs\python\python312\lib\site-packages (from copernicusmarine) (2026.3.0)
Requirement already satisfied: h5netcdf<2.0.0,>=1.4.0 in c:\users\aleks\appdata\local\programs\python\python312\lib\site-packages (from copernicusmarine) (1.8.1)
Requirement already satisfied: numpy>=1.23.0 in c:\users\aleks\appdata\roaming\python\python312\site-packages (from copernicusmarine) (2.1.3)
Collecting pydantic<3.0.0,>=2.9.1 (from copernicusmarine)
  Obtaining dependency information for pydantic<3.0.0,>=2.9.1 from https://files.pythonhosted.org/packages/01/d7/c3a52c61f5b7be648e919005820fbac33028c6149994cd64453f49951c17/pydantic-2.13.0-py3-none-any.whl.metadata
  Downloading pydantic-2.13.0-py3-none-any.whl.metadata (107 kB)
     ---------------------------------------- 0.0/107.9 kB ? eta -:--:--
     --- ------------------------------------ 10.2/107.9 kB ? eta -:--:--
     -------------- ---------------------- 41.0/107.9 kB 487.6 kB/s eta 0:00:01
     ------------------------------------ 107.9/107.9 kB 887.4 kB/s eta 0:00:00
Collecting pystac>=1.8.3 (from copernicusmarine)
  Obtaining dependency information for pystac>=1.8.3 from https://files.pythonhosted.org/packages/ad/b4/a9430e72bfc3c458e1fcf8363890994e483052ab052ed93912be4e5b32c8/pystac-1.14.3-py3-none-any.whl.metadata
  Downloading pystac-1.14.3-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: requests>=2.27.1 in c:\users\aleks\appdata\local\programs\python\python312\lib\site-packages (from copernicusmarine) (2.32.5)
Collecting semver>=3.0.2 (from copernicusmarine)
  Obtaining dependency information for semver>=3.0.2 from https://files.pythonhosted.org/packages/a6/24/4d91e05817e92e3a61c8a21e08fd0f390f5301f1c448b137c57c4bc6e543/semver-3.0.4-py3-none-any.whl.metadata
  Downloading semver-3.0.4-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: setuptools>=68.2.2 in c:\users\aleks\appdata\local\programs\python\python312\lib\site-packages (from copernicusmarine) (69.5.1)
Requirement already satisfied: tqdm>=4.65.0 in c:\users\aleks\appdata\local\programs\python\python312\lib\site-packages (from copernicusmarine) (4.67.1)
Requirement already satisfied: xarray>=2023.4.0 in c:\users\aleks\appdata\local\programs\python\python312\lib\site-packages (from copernicusmarine) (2026.2.0)
Collecting zarr>=2.13.3 (from copernicusmarine)
  Obtaining dependency information for zarr>=2.13.3 from https://files.pythonhosted.org/packages/de/7c/ba8ca8cbe9dbef8e83a95fc208fed8e6686c98b4719aaa0aa7f3d31fe390/zarr-3.1.6-py3-none-any.whl.metadata
  Downloading zarr-3.1.6-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: pandas<3,>=2 in c:\users\aleks\appdata\roaming\python\python312\site-packages (from arcosparse<0.5.0,>=0.4.2->copernicusmarine) (2.3.3)
Requirement already satisfied: pyarrow>=17.0.0 in c:\users\aleks\appdata\local\programs\python\python312\lib\site-packages (from arcosparse<0.5.0,>=0.4.2->copernicusmarine) (20.0.0)
Requirement already satisfied: botocore<1.43.0,>=1.42.30 in c:\users\aleks\appdata\roaming\python\python312\site-packages (from boto3>=1.26->copernicusmarine) (1.42.30)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\aleks\appdata\roaming\python\python312\site-packages (from boto3>=1.26->copernicusmarine) (1.0.1)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in c:\users\aleks\appdata\roaming\python\python312\site-packages (from boto3>=1.26->copernicusmarine) (0.16.0)
Requirement already satisfied: colorama in c:\users\aleks\appdata\local\programs\python\python312\lib\site-packages (from click!=8.2.0,<8.3.0,>=8.0.4->copernicusmarine) (0.4.6)
Requirement already satisfied: cloudpickle>=3.0.0 in c:\users\aleks\appdata\roaming\python\python312\site-packages (from dask>=2022->copernicusmarine) (3.1.2)
Requirement already satisfied: fsspec>=2021.09.0 in c:\users\aleks\appdata\local\programs\python\python312\lib\site-packages (from dask>=2022->copernicusmarine) (2024.3.1)
Requirement already satisfied: packaging>=20.0 in c:\users\aleks\appdata\local\programs\python\python312\lib\site-packages (from dask>=2022->copernicusmarine) (26.0)
Requirement already satisfied: partd>=1.4.0 in c:\users\aleks\appdata\local\programs\python\python312\lib\site-packages (from dask>=2022->copernicusmarine) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in c:\users\aleks\appdata\local\programs\python\python312\lib\site-packages (from dask>=2022->copernicusmarine) (6.0.2)
Requirement already satisfied: toolz>=0.12.0 in c:\users\aleks\appdata\local\programs\python\python312\lib\site-packages (from dask>=2022->copernicusmarine) (0.12.1)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\aleks\appdata\local\programs\python\python312\lib\site-packages (from pydantic<3.0.0,>=2.9.1->copernicusmarine) (0.6.0)
Collecting pydantic-core==2.46.0 (from pydantic<3.0.0,>=2.9.1->copernicusmarine)
  Obtaining dependency information for pydantic-core==2.46.0 from https://files.pythonhosted.org/packages/d1/84/4b6252e9606e8295647b848233cc4137ee0a04ebba8f0f9fb2977655b38c/pydantic_core-2.46.0-cp312-cp312-win_amd64.whl.metadata
  Downloading pydantic_core-2.46.0-cp312-cp312-win_amd64.whl.metadata (6.7 kB)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\aleks\appdata\local\programs\python\python312\lib\site-packages (from pydantic<3.0.0,>=2.9.1->copernicusmarine) (4.15.0)
Collecting typing-inspection>=0.4.2 (from pydantic<3.0.0,>=2.9.1->copernicusmarine)
  Obtaining dependency information for typing-inspection>=0.4.2 from https://files.pythonhosted.org/packages/dc/9b/47798a6c91d8bdb567fe2698fe81e0c6b7cb7ef4d13da4114b41d239f65d/typing_inspection-0.4.2-py3-none-any.whl.metadata
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: python-dateutil>=2.7.0 in c:\users\aleks\appdata\roaming\python\python312\site-packages (from pystac>=1.8.3->copernicusmarine) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\aleks\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.27.1->copernicusmarine) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\aleks\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.27.1->copernicusmarine) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\aleks\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.27.1->copernicusmarine) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\aleks\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.27.1->copernicusmarine) (2023.11.17)
Collecting donfig>=0.8 (from zarr>=2.13.3->copernicusmarine)
  Obtaining dependency information for donfig>=0.8 from https://files.pythonhosted.org/packages/0c/d5/c5db1ea3394c6e1732fb3286b3bd878b59507a8f77d32a2cebda7d7b7cd4/donfig-0.8.1.post1-py3-none-any.whl.metadata
  Downloading donfig-0.8.1.post1-py3-none-any.whl.metadata (5.0 kB)
Collecting google-crc32c>=1.5 (from zarr>=2.13.3->copernicusmarine)
  Obtaining dependency information for google-crc32c>=1.5 from https://files.pythonhosted.org/packages/df/c0/87c2073e0c72515bb8733d4eef7b21548e8d189f094b5dad20b0ecaf64f6/google_crc32c-1.8.0-cp312-cp312-win_amd64.whl.metadata
  Downloading google_crc32c-1.8.0-cp312-cp312-win_amd64.whl.metadata (1.8 kB)
Collecting numcodecs>=0.14 (from zarr>=2.13.3->copernicusmarine)
  Obtaining dependency information for numcodecs>=0.14 from https://files.pythonhosted.org/packages/1c/20/2fdec87fc7f8cec950d2b0bea603c12dc9f05b4966dc5924ba5a36a61bf6/numcodecs-0.16.5-cp312-cp312-win_amd64.whl.metadata
  Downloading numcodecs-0.16.5-cp312-cp312-win_amd64.whl.metadata (3.5 kB)
Requirement already satisfied: pytz>=2020.1 in c:\users\aleks\appdata\roaming\python\python312\site-packages (from pandas<3,>=2->arcosparse<0.5.0,>=0.4.2->copernicusmarine) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\aleks\appdata\roaming\python\python312\site-packages (from pandas<3,>=2->arcosparse<0.5.0,>=0.4.2->copernicusmarine) (2025.3)
Requirement already satisfied: locket in c:\users\aleks\appdata\local\programs\python\python312\lib\site-packages (from partd>=1.4.0->dask>=2022->copernicusmarine) (1.0.0)
Requirement already satisfied: six>=1.5 in c:\users\aleks\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.7.0->pystac>=1.8.3->copernicusmarine) (1.17.0)
Downloading copernicusmarine-2.3.0-py3-none-any.whl (125 kB)
   ---------------------------------------- 0.0/125.3 kB ? eta -:--:--
   ---------------------------------------- 125.3/125.3 kB 3.7 MB/s eta 0:00:00
Downloading arcosparse-0.4.2-py3-none-any.whl (26 kB)
Downloading pydantic-2.13.0-py3-none-any.whl (471 kB)
   ---------------------------------------- 0.0/471.9 kB ? eta -:--:--
   ------------------- -------------------- 235.5/471.9 kB 7.3 MB/s eta 0:00:01
   ---------------------------------------- 471.9/471.9 kB 5.9 MB/s eta 0:00:00
Downloading pydantic_core-2.46.0-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   -------- ------------------------------- 0.5/2.1 MB 13.8 MB/s eta 0:00:01
   ----------------- ---------------------- 0.9/2.1 MB 11.4 MB/s eta 0:00:01
   ------------------------- -------------- 1.3/2.1 MB 10.6 MB/s eta 0:00:01
   --------------------------------- ------ 1.7/2.1 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 9.4 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 9.4 MB/s eta 0:00:00
Downloading pystac-1.14.3-py3-none-any.whl (208 kB)
   ---------------------------------------- 0.0/208.5 kB ? eta -:--:--
   ---------------------------------------- 208.5/208.5 kB 6.2 MB/s eta 0:00:00
Downloading semver-3.0.4-py3-none-any.whl (17 kB)
Downloading zarr-3.1.6-py3-none-any.whl (295 kB)
   ---------------------------------------- 0.0/295.7 kB ? eta -:--:--
   ---------------------------------------- 295.7/295.7 kB 9.2 MB/s eta 0:00:00
Downloading donfig-0.8.1.post1-py3-none-any.whl (21 kB)
Downloading google_crc32c-1.8.0-cp312-cp312-win_amd64.whl (34 kB)
Downloading numcodecs-0.16.5-cp312-cp312-win_amd64.whl (801 kB)
   ---------------------------------------- 0.0/801.4 kB ? eta -:--:--
   ------------------------- ------------- 532.5/801.4 kB 11.1 MB/s eta 0:00:01
   --------------------------------------- 801.4/801.4 kB 10.1 MB/s eta 0:00:00
Using cached typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Installing collected packages: typing-inspection, semver, pydantic-core, numcodecs, google-crc32c, donfig, zarr, pystac, pydantic, arcosparse, copernicusmarine
  Attempting uninstall: pydantic-core
    Found existing installation: pydantic_core 2.18.1
    Uninstalling pydantic_core-2.18.1:
      Successfully uninstalled pydantic_core-2.18.1
  Attempting uninstall: pydantic
    Found existing installation: pydantic 2.7.0
    Uninstalling pydantic-2.7.0:
      Successfully uninstalled pydantic-2.7.0
Successfully installed arcosparse-0.4.2 copernicusmarine-2.3.0 donfig-0.8.1.post1 google-crc32c-1.8.0 numcodecs-0.16.5 pydantic-2.13.0 pydantic-core-2.46.0 pystac-1.14.3 semver-3.0.4 typing-inspection-0.4.2 zarr-3.1.6

In [ ]:
copernicusmarine.login()

INFO - 2026-04-13T18:59:09Z - Downloading Copernicus Marine data requires a Copernicus Marine username and password, sign up for free at: https://data.marine.copernicus.eu/register

Copernicus Marine username:Copernicus Marine password:

INFO - 2026-04-13T18:59:46Z - Credentials file stored in C:\Users\aleks\.copernicusmarine\.copernicusmarine-credentials.

True

In [12]:
bounding_box = [61.73, -2.62, 50.54, 11.7]
years = ['2023', '2024', '2025', '2026']


for year in years:
    print(f"--- YEAR {year} ---")

    tides_nc = f"tides_{year}.nc"
    
    copernicusmarine.subset(
        dataset_id="cmems_mod_glo_phy_anfc_0.083deg_PT1H-m", # PT1H - hourly data
        variables=["uo", "vo"],
        minimum_latitude=bounding_box[2], # S
        maximum_latitude=bounding_box[0], # N
        minimum_longitude=bounding_box[1], # W
        maximum_longitude=bounding_box[3], # E
        start_datetime=f"{year}-01-01T00:00:00",
        end_datetime=f"{year}-12-31T23:59:59",
        output_filename=tides_nc,
        force_download=True
    )

WARNING - 2026-04-13T19:11:01Z - 'force_download' has been deprecated.

--- YEAR 2023 ---

INFO - 2026-04-13T19:11:03Z - Selected dataset version: "202406"
INFO - 2026-04-13T19:11:03Z - Selected dataset part: "default"
100%|██████████| 234/234 [04:11<00:00,  1.08s/it]
WARNING - 2026-04-13T19:15:18Z - 'force_download' has been deprecated.

--- YEAR 2024 ---

INFO - 2026-04-13T19:15:21Z - Selected dataset version: "202406"
INFO - 2026-04-13T19:15:21Z - Selected dataset part: "default"
100%|██████████| 234/234 [04:12<00:00,  1.08s/it]
WARNING - 2026-04-13T19:19:35Z - 'force_download' has been deprecated.

--- YEAR 2025 ---

INFO - 2026-04-13T19:19:37Z - Selected dataset version: "202406"
INFO - 2026-04-13T19:19:37Z - Selected dataset part: "default"
100%|██████████| 198/198 [03:08<00:00,  1.05it/s]
WARNING - 2026-04-13T19:22:48Z - 'force_download' has been deprecated.

--- YEAR 2026 ---

INFO - 2026-04-13T19:22:50Z - Selected dataset version: "202406"
INFO - 2026-04-13T19:22:50Z - Selected dataset part: "default"
WARNING - 2026-04-13T19:22:50Z - Some of your subset selection [2026-01-01 00:00:00+00:00, 2026-12-31 23:59:59+00:00] for the time dimension exceed the dataset coordinates [2022-06-01 00:00:00+00:00, 2026-04-22 23:00:00+00:00]
100%|██████████| 82/82 [01:46<00:00,  1.30s/it]